name: papacapim  # Substitua pelo nome do seu projeto
description: Um aplicativo Flutter incrível!  # Opcional, mas recomendado

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter 
  timeago: ^3.6.1
  http: ^1.1.0
  provider: ^6.1.1  
